### ISSUE TITLE
reproduce question

### ISSUE THREAD

**Issue by XYAskWhy** [chaoyanghe/MiLeNAS#1]
In DARTS like methods, we optimize _w_ and _a_ alternatively. It seems that the very essence of your paper is to accumulate _w_ and _a_'s gradients, which is achieved by clearing optimizer_a's gradients immediately after clearing optimizer_w's gradients:
> `optimizer_w.zero_grad()`
`optimizer_a.zero_grad()`
`...`
`loss_w.backward()`
`optimizer_w.step()`
`...`
`loss_a.backward()`
`optimizer_a.step()`

Is this so?

**Comment by chaoyanghe** [comment]
No. This is not our algorithm and doesn't work. I will upload the code after the ICML rebuttal.

**Comment by QueeneTam** [comment]
> No. This is not our algorithm and doesn't work. I will upload the code after the ICML rebuttal.

Hello, your work is great! When will you release your code?

**Comment by my462** [comment]
> > No. This is not our algorithm and doesn't work. I will upload the code after the ICML rebuttal.
> 
> Hello, your work is great! When will you release your code?

Same question~2020 is passing away~

**Comment by chaoyanghe** [comment]
Hi @QueeneTam and @my462 sorry for the late submission. I just update the code.

I cannot get my code back due to the COVID-19. My full code lost in the server located at China. Now my every paper is open source. Please also check my other works at https://chaoyanghe.com/publications/
